### ISSUE TITLE
Predviđanje cena akcija

### ISSUE THREAD

**Issue by janosevicsm** [ftn-ai-lab/ri-2023-siit#28]
**Članovi tima**:
•	[Miloš Čuturić](https://github.com/cuturic01) SV11/2020 - Grupa 1
•	[Luka Đorđević](https://github.com/lukaDjordjevic01) SV14/2020 – Grupa 1
•	[Marko Janošević](https://github.com/janosevicsm) SV46/2020 – Grupa 3

**Asistent**: Marko Njegomir

**Problem koji se rešava**:
Predviđanje cena akcija korišćenjem mašinskog učenja je popularan i izazovan problem u finansijama i data-science-u. Cilj ovog projekta je korišćenje istorijskih cena akcija i povezanih podataka za obuku modela mašinskog učenja koji može precizno predvideti buduće cene akcija. Ovo može pomoći investitorima da donesu bolje informisane odluke o kupovini ili prodaji akcija i potencijalno da povećaju svoje prinose. Ideja je da se koriste različiti algoritmi i da se porede njihova predviđanja kako bi se dobili bolji i precizniji rezultati.

**Algoritmi**:
1.	Linearna regresija - Linearna regresija je često korišćen algoritam za predviđanje cena akcija. Funkcioniše tako što se linearna jednačina uklapa u podatke, sa ciljem da se minimizira razlika između predviđenih i stvarnih vrednosti. Ovaj algoritam je lak za implementaciju i tumačenje, ali možda neće obuhvatiti složene nelinearne odnose koji mogu postojati u cenama akcija.
2.	Stabla odluke - Stabla odluke su još jedan algoritam koji se može koristiti za predviđanje cena akcija. Radi tako što rekurzivno dele podatke na sve manje i manje podskupove na osnovu vrednosti karakteristika, na kraju stvarajući strukturu nalik stablu koja se može koristiti za predviđanje. Ovaj algoritam može da uhvati nelinearne odnose i interakcije između karakteristika, ali može da se uklapa u podatke i da bude osetljiv na male promene u podacima.
3.	Neuronske mreže - Neuronske mreže su moćan i složen algoritam koji se može koristiti za predviđanje cena akcija. Koriste više slojeva međusobno povezanih čvorova da bi naučili složene obrasce i odnose u podacima. Ovaj algoritam može da uhvati veoma nelinearne odnose i interakcije između karakteristika, ali može biti teško obučiti i interpretirati, i može zahtevati veliku količinu podataka i računarskih resursa da bi se postigle dobre performanse.
4.	Support Vector Machine (SVM) – SVM je algoritam učenja pod nadzorom koji se može koristiti za zadatke klasifikacije i regresije. U zadacima regresije, SVM pokušava da pronađe hiperravan koja razdvaja tačke podataka u različite klase dok maksimizira marginu između hiperravni i najbližih tačaka podataka. Hiperravan se zatim koristi za predviđanje novih tačaka podataka.

**Podaci koji se koriste**:
•	Podaci za ovaj projekat će biti prikupljeni pomoću [Alpha Vantage API](https://www.alphavantage.co/).

**Metrika za merenje performansi**:
•	Mean Squared Error (MSE) – Linearna regresija
•	Mean Absolute Error (MAE) – Stabla odluke
•	R-squared (R^2) – Neuronske mreže i SVM

**Validacija rešenja**:
•	Planirana je upotreba eksternih biblioteka kako bi se validirala rešenja.

**Comment by njmarko** [comment]
Оставите линк ка репозиторијуму.

Тема одобрена. Срећан рад! 👍

**Comment by janosevicsm** [comment]
- Backend
https://github.com/ThreeAmigosCoding/StockProphet
- Frontend
https://github.com/ThreeAmigosCoding/StockProphetFrontend
